package alimentos.view;

import alimentos.view.servicios.FrameCrearCarnico;

/**
 *
 * @author ESTUDIANTE
 */
public class CarnicosFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form Carnicos
     */
    public CarnicosFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto1Carnicos = new javax.swing.JLabel();
        botonCrearCarne = new javax.swing.JButton();

        texto1Carnicos.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        texto1Carnicos.setText("¿Qué desea hacer?...");

        botonCrearCarne.setBackground(new java.awt.Color(0, 255, 255));
        botonCrearCarne.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        botonCrearCarne.setText("Crear Carne");
        botonCrearCarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearCarneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(texto1Carnicos)
                .addGap(0, 201, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCrearCarne)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto1Carnicos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(botonCrearCarne)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearCarneActionPerformed
        FrameCrearCarnico carnico = new FrameCrearCarnico();
        carnico.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonCrearCarneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearCarne;
    private javax.swing.JLabel texto1Carnicos;
    // End of variables declaration//GEN-END:variables
}
