package alimentos.view;

import alimentos.view.servicios.FrameCrearFruta;
/**
 *
 * @author juan_
 */
public class FrutasFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form Animales
     */
    public FrutasFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Texto1PanelAnimalitos = new javax.swing.JLabel();
        botonCrearFruta = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(new javax.swing.border.MatteBorder(null));
        setMaximizable(true);
        setResizable(true);
        setTitle("Sección Animalitos del Zoo");

        Texto1PanelAnimalitos.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        Texto1PanelAnimalitos.setText("¿Qué desea hacer?...");

        botonCrearFruta.setBackground(new java.awt.Color(0, 255, 255));
        botonCrearFruta.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        botonCrearFruta.setText("Crear Fruta");
        botonCrearFruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearFrutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Texto1PanelAnimalitos)
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCrearFruta)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Texto1PanelAnimalitos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(botonCrearFruta)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearFrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearFrutaActionPerformed
        FrameCrearFruta fruta= new FrameCrearFruta();
        fruta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonCrearFrutaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Texto1PanelAnimalitos;
    private javax.swing.JButton botonCrearFruta;
    // End of variables declaration//GEN-END:variables
}
