package alimentos.view;

import alimentos.controller.ZonaAlimentos;
import alimentos.controller.clasesAlimentos.Carnicos;
import alimentos.controller.clasesAlimentos.Frutas;
import alimentos.controller.clasesAlimentos.Vegetales;
import alimentos.model.Db;
import alimentos.view.servicios.VerAlimentos;
import java.sql.SQLException;

/**
 *
 * @author juan_
 */
public class Pantalla extends javax.swing.JFrame {
    private FrutasFrame frutas;
    private VegetalesFrame vegetales;
    private CarnicosFrame carnicos;
    private VerAlimentos canasta;
    /**
     * Creates new form Pantalla
     * @throws java.sql.SQLException
     */
    public Pantalla(){
        initComponents();       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        texto1Bienvenida = new javax.swing.JLabel();
        texto2Bienvenida = new javax.swing.JLabel();
        menuBar1Epiko = new javax.swing.JMenuBar();
        Menu1Animales = new javax.swing.JMenu();
        opcionFrutas = new javax.swing.JCheckBoxMenuItem();
        opcionVegetales = new javax.swing.JCheckBoxMenuItem();
        opcionCarnicos = new javax.swing.JCheckBoxMenuItem();
        menuCanasta = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(204, 255, 255));
        escritorio.setBorder(new javax.swing.border.MatteBorder(null));
        escritorio.setForeground(new java.awt.Color(204, 255, 51));

        texto1Bienvenida.setBackground(new java.awt.Color(0, 0, 0));
        texto1Bienvenida.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        texto1Bienvenida.setForeground(new java.awt.Color(0, 105, 0));
        texto1Bienvenida.setText("¡Zona de Alimentos!");
        texto1Bienvenida.setBorder(new javax.swing.border.MatteBorder(null));

        texto2Bienvenida.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        texto2Bienvenida.setForeground(new java.awt.Color(49, 78, 255));
        texto2Bienvenida.setText("En la sección superior izquierda encontrarás la selección: {Frutas, Vegetales o Carnicos}");
        texto2Bienvenida.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        escritorio.setLayer(texto1Bienvenida, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(texto2Bienvenida, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(texto1Bienvenida))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(texto2Bienvenida)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(texto1Bienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(255, 255, 255)
                .addComponent(texto2Bienvenida)
                .addGap(245, 245, 245))
        );

        Menu1Animales.setText("Seleccionar");
        Menu1Animales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu1AnimalesActionPerformed(evt);
            }
        });

        opcionFrutas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        opcionFrutas.setSelected(false);
        opcionFrutas.setText("Frutas");
        opcionFrutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionFrutasActionPerformed(evt);
            }
        });
        Menu1Animales.add(opcionFrutas);

        opcionVegetales.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        opcionVegetales.setSelected(false);
        opcionVegetales.setText("Vegetales");
        opcionVegetales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionVegetalesActionPerformed(evt);
            }
        });
        Menu1Animales.add(opcionVegetales);

        opcionCarnicos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        opcionCarnicos.setText("Carnicos");
        opcionCarnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionCarnicosActionPerformed(evt);
            }
        });
        Menu1Animales.add(opcionCarnicos);

        menuCanasta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuCanasta.setText("Canasta");
        menuCanasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCanastaActionPerformed(evt);
            }
        });
        Menu1Animales.add(menuCanasta);

        menuBar1Epiko.add(Menu1Animales);

        setJMenuBar(menuBar1Epiko);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu1AnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu1AnimalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu1AnimalesActionPerformed

    private void opcionVegetalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionVegetalesActionPerformed
        if (opcionVegetales.isSelected()) {
            // Abrir la ventana ZooView si no está ya abierta
            if (vegetales == null || vegetales.isClosed()) {
                vegetales = new VegetalesFrame();
                escritorio.add(vegetales);
                vegetales.setVisible(true);
                try {
                    vegetales.setSelected(true);
                } catch (java.beans.PropertyVetoException e) {
                    e.printStackTrace();
                }
            }
        } else {
            // Cerrar la ventana ZooView si está abierta
            if (vegetales!= null && !vegetales.isClosed()) {
                try {
                    vegetales.setClosed(true);
                } catch (java.beans.PropertyVetoException e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_opcionVegetalesActionPerformed

    private void opcionFrutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionFrutasActionPerformed
        if (opcionFrutas.isSelected()) {
            // Abrir la ventana AnimalesView si no está ya abierta
            if (frutas == null || frutas.isClosed()) {
                frutas = new FrutasFrame();
                escritorio.add(frutas);
                frutas.setVisible(true);
                try {
                    frutas.setSelected(true);
                } catch (java.beans.PropertyVetoException e) {
                    e.printStackTrace();
                }
            }
        } else {
            // Cerrar la ventana AnimalesView si está abierta
            if (frutas != null && !frutas.isClosed()) {
                try {
                    frutas.setClosed(true);
                } catch (java.beans.PropertyVetoException e) {
                    e.printStackTrace();
                }
            }
        }

    }//GEN-LAST:event_opcionFrutasActionPerformed

    private void opcionCarnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionCarnicosActionPerformed
        if (opcionCarnicos.isSelected()) {
            // Abrir la ventana ZooView si no está ya abierta
            if (carnicos == null || carnicos.isClosed()) {
                carnicos = new CarnicosFrame();
                escritorio.add(carnicos);
                carnicos.setVisible(true);
                try {
                    carnicos.setSelected(true);
                } catch (java.beans.PropertyVetoException e) {
                    e.printStackTrace();
                }
            }
        } else {
            // Cerrar la ventana ZooView si está abierta
            if (carnicos!= null && !carnicos.isClosed()) {
                try {
                    carnicos.setClosed(true);
                } catch (java.beans.PropertyVetoException e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_opcionCarnicosActionPerformed

    private void menuCanastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCanastaActionPerformed
        if (menuCanasta.isSelected()) {
            // Abrir la ventana ZooView si no está ya abierta
            if (canasta == null || canasta.isClosed()) {
                canasta = new VerAlimentos();
                escritorio.add(canasta);
                canasta.setVisible(true);
                try {
                    canasta.setSelected(true);
                } catch (java.beans.PropertyVetoException e) {
                    e.printStackTrace();
                }
            }
        } else {
            // Cerrar la ventana ZooView si está abierta
            if (canasta!= null && !canasta.isClosed()) {
                try {
                    canasta.setClosed(true);
                } catch (java.beans.PropertyVetoException e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_menuCanastaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu1Animales;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar menuBar1Epiko;
    private javax.swing.JCheckBoxMenuItem menuCanasta;
    private javax.swing.JCheckBoxMenuItem opcionCarnicos;
    private javax.swing.JCheckBoxMenuItem opcionFrutas;
    private javax.swing.JCheckBoxMenuItem opcionVegetales;
    private javax.swing.JLabel texto1Bienvenida;
    private javax.swing.JLabel texto2Bienvenida;
    // End of variables declaration//GEN-END:variables
}
