/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package alimentos.view;

import alimentos.view.servicios.FrameCrearVegetal;
/**
 *
 * @author juan_
 */
public class VegetalesFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ZooView
     */
    public VegetalesFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto1Vegetales = new javax.swing.JLabel();
        botonCrearVegetales = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestión de el Zoo");

        texto1Vegetales.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        texto1Vegetales.setText("¿Qué desea hacer?...");

        botonCrearVegetales.setBackground(new java.awt.Color(0, 255, 255));
        botonCrearVegetales.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        botonCrearVegetales.setText("Crear Vegetales");
        botonCrearVegetales.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                botonCrearVegetalesAncestorRemoved(evt);
            }
        });
        botonCrearVegetales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearVegetalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto1Vegetales)
                .addContainerGap(190, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCrearVegetales)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto1Vegetales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(botonCrearVegetales)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearVegetalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearVegetalesActionPerformed
        FrameCrearVegetal vegetal = new FrameCrearVegetal();
        vegetal.setVisible(true);
        this.dispose();      
    }//GEN-LAST:event_botonCrearVegetalesActionPerformed

    private void botonCrearVegetalesAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_botonCrearVegetalesAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCrearVegetalesAncestorRemoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearVegetales;
    private javax.swing.JLabel texto1Vegetales;
    // End of variables declaration//GEN-END:variables
}
